.env, docker-compose.yml
PR is ensuring proper naming of the Backend docker image tag and adding it together with the Frontend one to the `.env` file as a way of implicitly documenting them.
Ticket: https://mekomsolutions.atlassian.net/browse/OZ-126
=> OZ-126: Added O3_BACKEND_TAG envvar.

.env, docker-compose.yml
https://mekomsolutions.atlassian.net/browse/MEDME-5
In order to provide custom O3 frontend config files, the SPA_CONFIG_URLS can be provided to point to as many files as needed.
=> MEDME-5: Tweak Ozone Docker to allow SPA_CONFIG_URLS override

proxy/resources/proxy-rules
Basically, the frontend container is setup to run as if it were always mounted at /, so to proxy it from a sub-URL, like /openmrs/spa/ we need to tell the web server to treat that as the context.
Without this change, the initial request goes to /openmrs/spahome, which doesn't get properly served (because this doesn't resolve to a URL). With this change, requests properly go to /openmrs/spa/home
=> Fix proxy-rules for the OpenMRS frontend

readme/manual-setup.md
This PR updates the documentation for setting up Ozone FOSS using manual setup guide.
- Switched O3_FRONTEND_TAG to use `3.0.0-beta.13` image
- Added O3_BACKEND_TAG
=> Simplifying copy pastes and setting correct frontend and backend versions in Manual Setup.

demo/docker-compose.yml, demo/eip/config/application.properties, demo/eip/routes/authenticate-to-openmrs-route.xml, demo/eip/routes/generate-demo-data-route.xml
Issue: https://mekomsolutions.atlassian.net/jira/software/c/projects/OZ/issues/OZ-348
This PR aligns the eip demo service with the upgraded `eip-client` by:
- Remove unnecessary eip/debezium (openmrs-watcher)configuration
- Mount to the correct config & routes path
=> OZ-348: Align `eip-demo` service with the upgraded `eip-client`.

docker-compose-senaite.yml
This PR changes the `SENAITE_SERVER_URL` from using the `SENAITE_HOSTNAME` environment variable to a hardcoded internal Docker network URL. This is to ensure that the `eip-openmrs-senaite` service can always reach the senaite service within the Docker network. Already `eip-odoo-openmrs` uses internal docker network URLs. see [here](https://github.com/ozone-his/ozone-docker-compose/blob/main/docker-compose-odoo.yml#L85-L86)
=> OZ-348: Update SENAITE_SERVER_URL to use internal Docker network URL for SENAITE service.

docker-compose-openmrs.yml
Issue: https://mekomsolutions.atlassian.net/jira/software/c/projects/OZ/issues/OZ-455
The assumption: OpenMRS takes 2 - 10 mins to initialize fully.
Based on that:
```
start_period + ( interval * retries) = 10 mins
```
`start_period`: This is the time to wait before counting retries. This is useful to give some time to the service to start up.
=> OZ-455: Update OpenMRS health check to use `/health/started` endpoint

docker-compose-common.yml
Issue: https://mekomsolutions.atlassian.net/jira/software/c/projects/OZ/issues/OZ-461
I've tested this and works well with the latest changes after the upgrade of EIP stack.
=> OZ-461: Upgrade Ozone Docker MariaDB to `v10.8`

docker-compose-superset.yml
This PR fixes the `superset-worker` docker-compose service which currently fails with the error:
```log
Error: No such option: --app
2024-02-14 15:56:54 You are using `--app` as an option of the worker sub-command:
2024-02-14 15:56:54 celery worker --app celeryapp <...>
2024-02-14 15:56:54 
2024-02-14 15:56:54 The support for this usage was removed in Celery 5.0. Instead you should use `--app` as a global option:
2024-02-14 15:56:54 celery --app celeryapp worker <...>
2024-02-14 15:56:54 Usage: celery worker [OPTIONS]
2024-02-14 15:56:54 Try 'celery worker --help' for help.
```
=> OZ-196: Fix `superset-worker` celery worker command

demo/eip/routes/generate-demo-data-route.xml
Added ShutdownServer bean which will be triggered from generate-demo-data-route after the data is generated. It will shutdown the server gracefully.
eip-client https://github.com/ozone-his/eip-client/pull/33 
ozone-docker-compose https://github.com/ozone-his/ozone-docker-compose/pull/96
=> OZ-476: Add shutdownHandler step in generate-demo-data-route.

scripts/destroy-demo.sh, scripts/start.sh, scripts/utils.sh
Issue: https://mekomsolutions.atlassian.net/browse/OZ-627
- Implemented a function to check if the Ozone project is running using Docker.
- Added logic to dynamically assign a numeric suffix to the project name (e.g., ozone_1, ozone_2) if the default project name is already in use.
Todos:
- Still need to take care of exposed ports conflicts, if there are any.
=> OZ-627: Add dynamic project name suffix for Ozone in Docker Compose

.env, docker-compose-odoo.yml, docker-compose-openmrs.yml, docker-compose-senaite.yml, scripts/ozone-urls-template.csv, scripts/start.sh, scripts/utils.sh
Issue: https://mekomsolutions.atlassian.net/jira/software/c/projects/OZ/issues/OZ-572
This PR does;
- Ensure O3 component URLs are set to HTTP for local Ozone instances
- Modify relevant environment variables and docker compose files
=> OZ-572: Update O3 component URL(s) to use right scheme when Ozone is running locally

docker-compose-common.yml, docker-compose-erpnext.yml
Logs:
```log
WARN[0000] /users/evil-x/ozone/ozone-pro/target/ozonepro-1.0.0-SNAPSHOT/run/docker/docker-compose-common.yml: `version` is obsolete
WARN[0000] /users/evil-x/ozone/ozone-pro/target/ozonepro-1.0.0-SNAPSHOT/run/docker/docker-compose-erpnext.yml: `version` is obsolete
```
=> OZ-464: Remove Docker compose `version` since it's obsolete.

scripts/stop-demo.sh
Updates stop script to use correct container names
=> OZ-627: Update `stop-demo.sh` to use exported project name 

.env, bundled-docker/frontend/Dockerfile, bundled-docker/frontend/startup.sh, docker-compose-openmrs.yml
Issue: https://mekomsolutions.atlassian.net/jira/software/c/projects/OZ/issues/OZ-698
This PR updates `/usr/share/nginx/html/ozone` to `/usr/share/nginx/html/configs` and updates references to `SPA_CONFIG_URLS` accordingly.
=> OZ-698: O3 frontend config files served in `configs/` instead of `ozone/`

scripts/start.sh
Issue: https://mekomsolutions.atlassian.net/browse/OZ-627
This PR ensures that the Docker Compose up command is re-applied when Ozone project is already running, thus ensures all services are up to date.
=> OZ-627: Ensure Docker Compose up command is re-applied when Ozone project is already running

bundled-docker/openmrs/Dockerfile, docker-compose-openmrs.yml
Ticket: https://mekomsolutions.atlassian.net/browse/OZ-760
=> OZ-760: Use 2.6.x-nightly-amazoncorretto-11 OpenMRS image.

bundled-docker/eip-erpnext-openmrs/Dockerfile, bundled-docker/erpnext/Dockerfile, bundled-docker/pom.xml
Issue: https://mekomsolutions.atlassian.net/browse/OZ-573
This PR removes ERPNext from bundled docker.
=> OZ-573: Remove ERPNext from bundled docker

docker-compose-restore-sso.yml, docker-compose-restore.yml, scripts/utils.sh
This PR addresses issues encountered while testing the restore process for Ozone. It adds restore profiles for instances, which include SENAITE with data in PostgreSQL and Keycloak.  
Ticket https://mekomsolutions.atlassian.net/browse/OZ-331
=> OZ-331: Add a SENAITE and Keycloak restore profiles

scripts/start.sh
Ticket: https://mekomsolutions.atlassian.net/browse/OZ-331?focusedCommentId=46772
This PR adds a validation step for the minimum docker compose version on a host machine.
=> OZ-331: Add a validation step for minimum docker compose version

docker-compose-odoo.yml, docker-compose-orthanc.yml
This Pr fixes an issue with the whole deployment becoming inaccessible after enabling Orthanc. Ticket https://mekomsolutions.atlassian.net/browse/OZ-813
=> OZ-813: Fix network conflic issue with Orthanc and Odoo

docker-compose-erpnext.yml
Issue: https://mekomsolutions.atlassian.net/browse/OZ-873
This PR fixes ERPNext data flows, adds the missing config `openmrs.baseUrl`
=> OZ-873: Add `OPENMRS_BASEURL` environment variable

docker-compose-openmrs.yml
Issue: https://mekomsolutions.atlassian.net/browse/OZ-838
This upgrades OpenMRS Core docker image to version `2.7.4`
=> OZ-838: Use `openmrs-core:2.7.4-amazoncorretto-17`

bundled-docker/openmrs/Dockerfile, docker-compose-openmrs.yml, openmrs/log4j2.xml
This adds a log4j configuration to output logs in JSON for easy collection. It is part of the ground work for https://openmrs.atlassian.net/browse/HIS-28
=> OZ-597: Output OpenMRS console logs as JSON

docker-compose-keycloak.yml
As part of testing the Backup & Restore process with no demo data, it appears that loading the KC config at every reboot is creating issues. Basically, if I create a new KC user - which is necessary when running without demo data - then upon next restart, the user will be gone.
As discussed here in Slack: https://mekomsolutions.slack.com/archives/G421UNF5L/p1754639024623649?thread_ts=1754589741.915639&cid=G421UNF5L
> I’d say that there is 3 things that users would do:
(1) Evaluation
(2) Development/config/implement
(3) Run in prod.
> For the users who would do the (1), then it’s possible they are trying Ozone one day, stopping it, starting it again the next day to resume their testing etc...
In that sense, having the KC users to stick is probably preferable.
> For (2), I can see that …
=> OZ-773: Keycloak config loading strategy should default to `IGNORE_EXISTING`

bundled-docker/grafana-agent/Dockerfile, bundled-docker/pom.xml, docker-compose-logging-agent.yml, pom.xml
This PR adds a Dockerfile to allow bundling of config for the Grafana Agent.
=> HIS-28: Add a Dockerfile to bundle grafana-agent

docker-compose-keycloak.yml
The PR remove the unsupported --log-console-json-format,reverts keycloak.migration.strategy to IGNORE_EXISTING
=> HIS-28: Remove the unsupported --log-console-json-format and revert keycloak.migration.strategy to IGNORE_EXISTING

bundled-docker/proxy/default.conf.template, proxy/default.conf.template
This increases the buffer size for NGINX, which should hopefully resolve the 502 error when trying to access Superset and Odoo using the Links in the EMR.
=> HIS: Fix 502 error when Odoo or Superset are accessed from OpenMRS for Distro HIS

scripts/ozone-urls-template.csv, scripts/utils.sh
Ticket: https://mekomsolutions.atlassian.net/browse/OZ-960
=> OZ-960: Fix typos in `start.sh` script.
