README.md
docker-compose.yml
proxy/Dockerfile
proxy/confs/030-8069.conf
proxy/resources/httpd.conf
proxy/resources/proxy-rules

Also adds support for MYSQL as the eip management DB

OZ-41:Enable TLS on Odoo

---

readme/manual-setup.md
start-demo.sh

Ticket: https://mekomsolutions.atlassian.net/browse/OZ-109

OZ-109: Updated group ID in Quick Start script and Manual Setup.

---

.env

Ticket: https://mekomsolutions.atlassian.net/browse/OZ-111

OZ-111: Updating SENAITE route name

---

docker-compose.yml
proxy/confs/040-8081.conf
start-demo.sh

Ticket: https://mekomsolutions.atlassian.net/browse/OZ-120

OZ-120: SENAITE HTTP requests rewritten to use SSL (in Gitpod only).

---

.gitignore
assembly.xml
pom.xml

https://mekomsolutions.atlassian.net/browse/OZ-130

OZ-130: Make ozone-docker a Maven project.

---

destroy-demo.sh
readme/manual-setup.md
start-demo.sh

Ticket: https://mekomsolutions.atlassian.net/browse/OZ-132

OZ-132: Quick start and manual setup to use release 1.0.0-alpha.1.

---

docker-compose.yml
readme/manual-setup.md
start-demo.sh

Ticket: https://mekomsolutions.atlassian.net/browse/OZ-132

 OZ-132: Quick start and manual setup's renamed O3_FRONTEND_TAG set to 3.0.0-beta.2.

---

docker-compose.yml

Ticket: https://mekomsolutions.atlassian.net/browse/OZ-126
Depends on PR: https://github.com/openmrs/openmrs-core/pull/4275

OZ-126: Using mainstream OpenMRS backend docker image.

---

docker-compose.yml

Ticket https://mekomsolutions.atlassian.net/browse/OZ-165

OZ-165: Add restart directive to ensure services restart on reboot

---

destroy-demo.sh
start-demo.sh

Refer to [OZ-49](https://mekomsolutions.atlassian.net/browse/OZ-49)
Responsible ticket: https://mekomsolutions.atlassian.net/browse/OZ-120
Additional conversation via [Slack](https://mekomsolutions.slack.com/archives/G421UNF5L/p1680593461771949) !
[OZ-49]: https://mekomsolutions.atlassian.net/browse/OZ-49?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OZ-120: Improved Docker version check in start demo script.

---

docker-compose.yml
pom.xml
readme/manual-setup.md
start-demo.sh

Double commit to release Ozone Docker https://mekomsolutions.atlassian.net/browse/OZ-149

OZ-149:  Release of Ozone Docker

---

demo/eip/config/application.properties
demo/eip/routes/generate-demo-data-route.xml
readme/manual-setup.md
start-demo.sh

Ticket: https://mekomsolutions.atlassian.net/browse/OZ-166

OZ-166: Adding an EIP route to trigger demo data generation.

---

destroy-demo.sh
docker-compose.yml
pom.xml
readme/manual-setup.md
start-demo.sh

Ticket https://mekomsolutions.atlassian.net/browse/OZ-263

Release 1.0.0.alpha.5

---

docker-compose.yml

Fixes https://mekomsolutions.atlassian.net/browse/OZ-198

OZ-198: Fixed 404 with /openmrs/spa through Traefik.

---

docker-compose.yml

Ticket: https://mekomsolutions.atlassian.net/browse/OZ-363

OZ-363: Improve MySQL binlog settings

---

proxy/default.conf.template

Followup commit for: https://mekomsolutions.atlassian.net/browse/OZ-457

OZ-457: SENAITE HTTP requests rewritten to use SSL (in Gitpod only)

---

proxy/default.conf.template

Ticket: https://mekomsolutions.atlassian.net/browse/OZ-457

OZ-457: Fix proxy_pass SENAITE rule for Nginx.

---

README.md

Ticket → [OZ-354](https://mekomsolutions.atlassian.net/browse/OZ-354)
[OZ-354]: https://mekomsolutions.atlassian.net/browse/OZ-354?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OZ-354: Updated README with new "ozone-docker-compose".

---

proxy/default.conf.template

Ticket: https://mekomsolutions.atlassian.net/browse/OZ-457

OZ-457: Followup commit to Fix issue with Nginx crashing when SENAITE server isn't available

---

proxy/default.conf.template
proxy/docker-compose.yml
scripts/start.sh

Ticket: https://mekomsolutions.atlassian.net/browse/OZ-457

OZ-457: Fixed issue with Nginx crashing when running the SENAITE service locally

---

.env

Ticket → [OZ-484](https://mekomsolutions.atlassian.net/browse/OZ-484)
[OZ-484]: https://mekomsolutions.atlassian.net/browse/OZ-484?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OZ-484: Use O3 Ref App 3.0.0-beta.17

---

.env

Ticket → [OZ-484](https://mekomsolutions.atlassian.net/browse/OZ-484)
[OZ-484]: https://mekomsolutions.atlassian.net/browse/OZ-484?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OZ-484: Use O3 Ref App 3.0.0-beta.18

---

.env
docker-compose-common.yml
docker-compose-erpnext.yml
scripts/utils.sh

-  Adds `eip-erpnext-openmrs` docker-compose integration service.

OZ-464: Add `eip-erpnext-openmrs` docker compose service.

---

docker-compose-erpnext.yml

PR introduces changes necessary for testing https://mekomsolutions.atlassian.net/browse/OZ-556

OZ-556: Remove deploy section from docker-compose-erpnext

---

.env

Ticket → [OZ-571](https://mekomsolutions.atlassian.net/browse/OZ-571)
[OZ-571]: https://mekomsolutions.atlassian.net/browse/OZ-571?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OZ-571: Use O3 Ref App 3.0.0-beta.20

---

.env

Ticket: https://mekomsolutions.atlassian.net/browse/OZ-625

OZ-625: Use O3 Ref App 3.0.0-beta.21

---

docker-compose-odoo.yml

JIRA: https://mekomsolutions.atlassian.net/browse/OZ-655

OZ-545: Add `camel-openmrs-fhir` configs for `eip-odoo-openmrs` docker compose service

---

.env

Ticket: https://mekomsolutions.atlassian.net/browse/OZ-670

OZ-670: O3_DOCKER_IMAGE_TAG to point to nightly.

---

proxy/default.conf.template

Issue: https://mekomsolutions.atlassian.net/jira/software/c/projects/OZ/issues/OZ-698

OZ-627: Update variable name from `$fhir-odoo` to `$fhirOdoo`

---

docker-compose-senaite-sso.yml

Issue: https://mekomsolutions.atlassian.net/browse/OZ-573
This PR renames `senaite-ozonepro` to `senaite-sso`

OZ-573: Rename `senaite-ozonepro` to `senaite-sso`

---

docker-compose-openmrs-sso.yml
scripts/utils.sh

This PR removes trailing backslash from `OPENMRS_FRONTEND_CONFIG_PATH` env var

OZ-573: Remove `OPENMRS_FRONTEND_CONFIG_PATH` trailing backslash

---

docker-compose-senaite.yml

JIRA: https://mekomsolutions.atlassian.net/browse/OZ-747

OZ-747: Add user & password credentials for `docker-compose-senaite.yml`

---

.env
bundled-docker/openmrs/Dockerfile
docker-compose-openmrs.yml

Ticket: https://mekomsolutions.atlassian.net/browse/OZ-760

OZ-760: Use O3_DOCKER_IMAGE_TAG `nightly` and OpenMRS core `nightly-amazoncorretto-11`

---

proxy/docker-compose.yml

Issue:https://mekomsolutions.atlassian.net/browse/OZ-753
This PR removes unused previously Superset port 8088 from Ozone proxy + some cleanups

OZ-753: Remove unused mapped port 8088 from Ozone proxy

---

.env
bundled-docker/frontend/Dockerfile
bundled-docker/openmrs/Dockerfile
docker-compose-openmrs.yml

https://mekomsolutions.atlassian.net/browse/OZ-790
Sets the images to be 3.2.1.
@corneliouzbett , is that going to work with Bundled Docker?

OZ-790: Use Ref App 3.2.1

---

proxy/default.conf.template

This PR fixes too many redirects issue.

OZ-742: Configure NGINX upstreams for OpenMRS frontend and backend services

---

scripts/start.sh

Issue: https://mekomsolutions.atlassian.net/browse/OZ-349
This PR adds a step to pull the demo docker image to start script.

OZ-349: Add a step to pull demo docker image to start script

---

.env
docker-compose-odoo-sso.yml
docker-compose-odoo.yml

Issue: https://openmrs.atlassian.net/browse/HIS-19
This PR adds the ability to override Odoo addons via environment variable

HIS-19: Add support to override Odoo addons via environment variable

---

docker-compose-keycloak.yml
proxy/default.conf.template

Issue: https://mekomsolutions.atlassian.net/browse/OZ-776
This PR updates Nginx configs to dynamically update forwarded protocol based on `GITPOD_ENV`.
Depends on #189 for app urls to be updated accordingly.

OZ-776: Update Nginx configuration to dynamically update forwarded protocol based on `GITPOD_ENV`
